# Charging Animation & Recovery Graphics
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888

# Display & Graphics Core Architecture
TARGET_USES_QCOM_DISPLAY_BSP := true
TARGET_USES_GRALLOC4 := true
TARGET_USES_HWC2 := true
TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true
MAX_VIRTUAL_DISPLAY_DIMENSION := 4096
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3

# Color & Metadata Profiles (Crucial for SM6225 Screen Rendering)
TARGET_USES_COLOR_METADATA := true
TARGET_HAS_WIDE_COLOR_DISPLAY := true
TARGET_HAS_HDR_DISPLAY := false
TARGET_USES_DISPLAY_RENDER_INTENTS := true
TARGET_USE_COLOR_MANAGEMENT := true
SF_WCG_COMPOSITION_DATA_SPACE := 143261696

# Post-Processing & Driver Tweaks
TARGET_USES_DRM_PP := true
